name: Release Fabric

on:
  issues:
    types: [opened, reopened]

jobs:
  releaseFabric:

    runs-on: ubuntu-latest

    container:
      image: openjdk:21-jdk
      options: --user root

    steps:
      - uses: actions/checkout@v2.2.0
      - run: |
          chmod +x ./gradlew
          ./gradlew :fabric:build --stacktrace
