name: Release

on: push

jobs:
  release:

    runs-on: ubuntu-latest

    container:
      image: openjdk:17-jdk
      options: --user root

    steps:
      - uses: actions/checkout@v2.2.0
      - run: |
          chmod +x ./gradlew
          ./gradlew build 

      - name: hi
        uses: actions/upload-artifact@v4
        with:
           name: my-artifact
           path: build/libs/
